security:
    encoders:
        bcrypt:
            algorithm: bcrypt
            cost: 12
    providers:
        users:
            id: 'App\Infrastructure\User\Auth\AuthProvider'

    firewalls:
      dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false

      api_doc:
        pattern:  ^/api/doc
        stateless: true
        anonymous: true

      api_auth:
        pattern:  ^/api/auth
        stateless: true
        anonymous: true

      api_signup:
        pattern:  ^/api/signup
        stateless: true
        anonymous: true

      api_secured:
        pattern:  ^/api
        provider: users
        stateless: true
        guard:
          authenticators:
            - 'App\Infrastructure\User\Auth\Guard\TokenAuthenticator'

    access_control:
      - { path: ^/api/doc,          roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api/signup,       roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api/auth,         roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api/,             roles: IS_AUTHENTICATED_FULLY       }
      - { path: ^/,                 roles: ROLE_USER }
