version: '3'

services:
  nginx:
    build:
      context: ./docker/development
      dockerfile: nginx.docker
    volumes:
      - .:/app
    depends_on:
      - php-fpm
    ports:
      - "8080:80"

  php-fpm:
    build:
      context: ./docker/development
      dockerfile: php-fpm.docker
    volumes:
      - .:/app
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=gatekeeper.local"
    depends_on:
      - postgres

  workers:
    build:
      context: ./docker/development
      dockerfile: php-cli.docker
    volumes:
      - .:/app
      - composer_data:/root/.composer/cache
    depends_on:
      - postgres
      - rabbitmq
    command: ['/app/bin/console', 'messenger:consume', 'events', '-vv']

  postgres:
    image: postgres:11.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gatekeeper
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: gatekeeper
    ports:
      - "54321:5432"

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_logs:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
  rabbitmq_data:
  rabbitmq_logs:
  composer_data:
