services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $queryBus: '@tactician.commandbus.query'
            $commandBus: '@tactician.commandbus.command'

    _instanceof:
        App\Infrastructure\Shared\Bus\Command\CommandHandler:
            public: true
            tags:
                - { name: tactician.handler, typehints: true, bus: command }

        App\Infrastructure\Shared\Bus\Query\QueryHandler:
            public: true
            tags:
                - { name: tactician.handler, typehints: true, bus: query }

    App\:
        resource: '../src/*'
        exclude: '../src/**/{Migrations,EventSubscriber}'

    App\UI\Http\Rest\Controller\:
        resource: '../src/UI/Http/Rest/Controller'
        tags: [ 'controller.service_arguments' ]

    App\UI\Http\Rest\EventSubscriber\ExceptionSubscriber:
        arguments:
            - "%kernel.environment%"
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception' }

    App\UI\Http\Rest\EventSubscriber\JsonBodyParserSubscriber:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest', priority: 100 }
