services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        App\Application\Command\CommandHandler:
            public: true
            tags:
                - { name: messenger.message_handler, bus: messenger.bus.command }

        App\Application\Query\QueryHandler:
            public: true
            tags:
                - { name: messenger.message_handler, bus: messenger.bus.query }

        App\Infrastructure\Shared\Bus\Event\EventHandler:
            public: true
            tags:
                - { name: messenger.message_handler, bus: messenger.bus.event.async }

    App\:
        resource: '../src/*'
        exclude: '../src/**/{Migrations,EventSubscriber}'

    App\Infrastructure\Shared\Bus\Command\MessengerCommandBus:
        arguments:
            - '@messenger.bus.command'

    App\Infrastructure\Shared\Bus\Query\MessengerQueryBus:
        arguments:
            - '@messenger.bus.query'

    App\Infrastructure\Shared\Bus\Event\MessengerEventBus:
        arguments:
            - '@messenger.bus.event.async'

    App\UI\Http\Rest\Controller\:
        resource: '../src/UI/Http/Rest/Controller'
        tags: [ 'controller.service_arguments' ]

    App\UI\Http\Rest\EventSubscriber\ExceptionSubscriber:
        arguments:
            - "%kernel.environment%"
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception' }

    App\UI\Http\Rest\EventSubscriber\JsonBodyParserSubscriber:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest', priority: 100 }
